### ISSUE TITLE
To do for Milestone 1

### ISSUE THREAD

**Issue by jonthemango** [jonthemango/pet_clinic#1]
Architecture and Continuous Integration (Due Feb 6th)
- [x] Basic Architecture
    - [x] Measure LOCs and number of classes
    - [x] Manually describe and diagram the main components
- [x] Setup the project inside Jenkins (show screenshots of it working)
     - [x] Run all the existing tests
     - [x] Setup static analysis tools
     - [x] Measure test coverage 

Describe the overall state of testing on the project (Due 6th) For each of the categories below: Provide a brief description, a snippet of actual code, a link to the code on GitHub. You may also provide a diagram if helpful
- [x] How long does it take to run all the tests?
- [x] Which are the longest running tests?
- [x] Dependencies
     - [x] Are there any inappropriate dependencies that make tests run for a long time?
     - [x] Are mocks used?
- [x] Are any tests flaky? ie they fail and pass on the same build.
- [x] Are there parts of the system with no tests? Why? Should there be tests?
- [x] Do some tests miss critical behaviour or functionality that should be tested?
- [x] Are getters/setters tested?
- [x] Do new commits have tests?
