### ISSUE TITLE
Milestone 3 

### ISSUE THREAD

**Issue by jonthemango** [jonthemango/pet_clinic#3]
- [x] Setup sqlite 
- [x] Determine where the calls to the old datastore are in the code
- [x] At each stage write tests that show your migration and consistency checker is working
- [x] Make sure to do incremental commits as your work
- [x] Write a forklift to move over old data to new data
- [x] Write a consistency checker that ensures that old data is consistent with new data. 
- [x] If it is inconsistent update new with old. 
- [x] Run it periodically and asynchronously across the entire old dataset (incremental replication)
- [x] Shadow Writes. Write directly to new datastore. 
- [x] Create a shadow writes consistency checker to ensure that only changes in old datastore are consistent in new datastore 
- [x] Shadow Reads for Validation
- [x] Read from old datastore and new datastore
- [x] Immediately return the old datastore result
- [x] Asynchronously check that the new datastore and old datastore returned the same result (Shadow reads consistency checker)
- [x] Update the new datastore if the results are not the same
- [x] Read and write from the new datastore
- [x] Migrate the data and consistency checker in the production
- [x] Run the checkers
- [ ] Remove the old datastore when your checkers are above a threshold
- [ ] Long-term consistency checker [2 additional marks]
- [ ] Re-purpose the consistency checker to keep a hash record of some unit of the data instead of the old datastore
- [ ] The hash consistency checker should be substantially smaller than the old datastore
